Using a newer version of node (v4.2.1) causes an error when running this test.
     TypeError: Cannot assign to read only property 'eval' of monica

It happens on references.js, in the getPropMethod. Line 273, when trying to set baseRef.eval property.